# Generated by Django 5.2.4 on 2025-10-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SentimentAnalysisResults',
            new_name='SentimentAnalysisResult',
        ),
        migrations.RenameField(
            model_name='sentimentanalysisresult',
            old_name='processing_time',
            new_name='processing_time_ms',
        ),
    ]
